### ISSUE TITLE
[分享] 主题：BNBChain跨链攻击事件深度分析-攻击者选择高度为110217401的区块到底有什么讲究？

### ISSUE THREAD

**Issue by ajoey91** [rebase-network/Rebase-University#4]
## 日期
2022.10.25

## 时间 
21:00PM
## 主题
安全分析

## 项目
BNBChain跨链攻击事件深度分析-攻击者选择高度为110217401的区块到底有什么讲究？

## 分享人

SharkTeam

## 阅读材料

https://m.chainaegis.com/home/news/detail?contentId=237

**Comment by xrdavies** [comment]
![Rebase大学-20221025](https://user-images.githubusercontent.com/1884084/197269781-37ece71f-a534-4373-ac01-73319629ea81.png)
